#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef DATAMANAGERSDK_SWIFT_H
#define DATAMANAGERSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="DataManagerSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS("_TtC14DataManagerSDK10EventModel")
@interface EventModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;

SWIFT_CLASS("_TtC14DataManagerSDK6DMCart")
@interface DMCart : EventModel
/// 상품 코드
@property (nonatomic, copy) NSString * _Nonnull productId;
/// 상품 이름
@property (nonatomic, copy) NSString * _Nonnull productName;
/// 상품 가격
@property (nonatomic) NSInteger productPrice;
/// 상품 이미지 URL
@property (nonatomic, copy) NSString * _Nonnull productImageUrl;
/// 상품 URL
@property (nonatomic, copy) NSString * _Nonnull productUrl;
/// 상품 수량
@property (nonatomic) NSInteger productQty;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14DataManagerSDK13DMCustomEvent")
@interface DMCustomEvent : EventModel
- (nonnull instancetype)initWithEventName:(NSString * _Nonnull)eventName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14DataManagerSDK14DMDeepLinkOpen")
@interface DMDeepLinkOpen : EventModel
- (nonnull instancetype)initWithPvInName:(NSString * _Nonnull)pvInName deepLink:(NSString * _Nonnull)deepLink OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, DMDefaultParams, open) {
  DMDefaultParamsId = 0,
  DMDefaultParamsType = 1,
  DMDefaultParamsDttm = 2,
  DMDefaultParamsTriggerCode = 3,
  DMDefaultParamsSessionId = 4,
};

typedef SWIFT_ENUM(NSInteger, DMEventType, open) {
/// 방문, 페이지 로드
  DMEventTypePageView = 0,
/// 본상품, 상품 상세보기
  DMEventTypeViewedProduct = 1,
/// 회원가입
  DMEventTypeSignUp = 2,
/// 로그인
  DMEventTypeSignIn = 3,
/// 회원정보 수정
  DMEventTypeModifyUser = 4,
/// 회원탈퇴
  DMEventTypeSignOut = 5,
/// 장바구니
  DMEventTypeCart = 6,
/// 찜
  DMEventTypeFavorite = 7,
/// 결제
  DMEventTypeOrder = 8,
/// 결제 이탈
  DMEventTypeOrderOut = 9,
/// 결제(주문) 취소
  DMEventTypeOrderCancel = 10,
/// 설치
  DMEventTypeInstall = 11,
/// 실행
  DMEventTypeVisit = 12,
/// 종료
  DMEventTypeOut = 13,
/// 딥링크로 앱 오픈
  DMEventTypeDeepLinkOpen = 14,
/// 사용자 커스텀 이벤트
  DMEventTypeCustom = 15,
};


SWIFT_CLASS("_TtC14DataManagerSDK10DMFavorite")
@interface DMFavorite : EventModel
@property (nonatomic, copy) NSString * _Nonnull productId;
@property (nonatomic, copy) NSString * _Nonnull productName;
@property (nonatomic) NSInteger productPrice;
@property (nonatomic, copy) NSString * _Nonnull imageUrl;
@property (nonatomic, copy) NSString * _Nonnull productUrl;
@property (nonatomic) NSInteger productQty;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14DataManagerSDK9DMInstall")
@interface DMInstall : EventModel
- (nonnull instancetype)initWithReferrer:(NSString * _Nullable)referrer OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14DataManagerSDK16DMModifyUserInfo")
@interface DMModifyUserInfo : EventModel
@property (nonatomic, copy) NSString * _Nonnull memberId;
@property (nonatomic, copy) NSString * _Nonnull memberName;
@property (nonatomic, copy) NSString * _Nonnull phoneNumber;
@property (nonatomic, copy) NSString * _Nonnull email;
@property (nonatomic) BOOL smsAllowed;
@property (nonatomic) BOOL emailAllowed;
@property (nonatomic, copy) NSString * _Nonnull birthDay;
@property (nonatomic, copy) NSString * _Nonnull gender;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class DMProduct;

SWIFT_CLASS("_TtC14DataManagerSDK7DMOrder")
@interface DMOrder : EventModel
@property (nonatomic, copy) NSArray<DMProduct *> * _Nonnull products;
@property (nonatomic, copy) NSString * _Nonnull orderId;
@property (nonatomic, copy) NSString * _Nonnull zipCode;
@property (nonatomic, copy) NSString * _Nonnull phoneNumber;
@property (nonatomic, copy) NSString * _Nonnull address;
@property (nonatomic) NSInteger totalPrice;
@property (nonatomic) NSInteger totalQty;
@property (nonatomic, copy) NSString * _Nonnull paymentMethod;
@property (nonatomic, copy) NSString * _Nonnull memberName;
@property (nonatomic, copy) NSString * _Nonnull email;
@property (nonatomic, copy) NSString * _Nonnull memberId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14DataManagerSDK13DMOrderCancel")
@interface DMOrderCancel : EventModel
@property (nonatomic, copy) NSArray<DMProduct *> * _Nonnull products;
@property (nonatomic, copy) NSString * _Nonnull orderId;
@property (nonatomic, copy) NSString * _Nonnull memberId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14DataManagerSDK10DMOrderOut")
@interface DMOrderOut : EventModel
@property (nonatomic, copy) NSArray<DMProduct *> * _Nonnull products;
@property (nonatomic, copy) NSString * _Nonnull memberId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14DataManagerSDK5DMOut")
@interface DMOut : EventModel
- (nonnull instancetype)initWithPvOutName:(NSString * _Nonnull)pvOutName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14DataManagerSDK10DMPageView")
@interface DMPageView : EventModel
- (nonnull instancetype)initWithPvInName:(NSString * _Nonnull)pvInName pvOutName:(NSString * _Nonnull)pvOutName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, DMParams, open) {
/// 생일
  DMParamsBirthDay = 0,
/// Email
  DMParamsEmail = 1,
/// Email 수신 여부
  DMParamsEmailAllowed = 2,
/// 성별
  DMParamsGender = 3,
/// 사용자(회원) ID
  DMParamsMemberId = 4,
/// 사용자(회원) 이름
  DMParamsMemberName = 5,
/// 주문 번호
  DMParamsOrderId = 6,
/// 총 결제 금액
  DMParamsPaymentAmount = 7,
/// 결제 수단
  DMParamsPaymentMethod = 8,
/// 핸드폰(전화) 번호
  DMParamsPhoneNumber = 9,
/// 상품 코드
  DMParamsProductId = 10,
/// 상품 이미지 URL
  DMParamsProductImageUrl = 11,
/// 상품명
  DMParamsProductName = 12,
/// 상품 가격
  DMParamsProductPrice = 13,
/// 상품 수량
  DMParamsProductQty = 14,
/// 상품 목록
  DMParamsProducts = 15,
/// 상품 URL
  DMParamsProductUrl = 16,
/// SMS 수신 여부
  DMParamsSmsAllowed = 17,
/// 우편번호
  DMParamsZipCode = 18,
/// 주소
  DMParamsAddress = 19,
/// 총 가격
  DMParamsTotalPrice = 20,
/// 총 수량
  DMParamsTotalQuantity = 21,
/// 커스텀 이벤트의 이벤트 명
  DMParamsEventName = 22,
/// 화면 전환시 전환된 화면 이름
  DMParamsPvInName = 23,
/// 화면 전환시 이전 화면 이름
  DMParamsPvOutName = 24,
/// 화면 오픈을 deep link로 진행한 경우 deep link URL
  DMParamsDeeplink = 25,
/// referrer 값
  DMParamsReferrer = 26,
};


SWIFT_CLASS("_TtC14DataManagerSDK9DMProduct")
@interface DMProduct : EventModel
@property (nonatomic, copy) NSString * _Nonnull productId;
@property (nonatomic, copy) NSString * _Nonnull productName;
@property (nonatomic) NSInteger productPrice;
@property (nonatomic, copy) NSString * _Nonnull imageUrl;
@property (nonatomic, copy) NSString * _Nonnull productUrl;
@property (nonatomic) NSInteger productQty;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14DataManagerSDK8DMSignIn")
@interface DMSignIn : EventModel
@property (nonatomic, copy) NSString * _Nonnull memberId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14DataManagerSDK9DMSignOut")
@interface DMSignOut : EventModel
@property (nonatomic, copy) NSString * _Nonnull memberId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14DataManagerSDK8DMSignUp")
@interface DMSignUp : EventModel
@property (nonatomic, copy) NSString * _Nonnull memberId;
@property (nonatomic, copy) NSString * _Nonnull memberName;
@property (nonatomic, copy) NSString * _Nonnull phoneNumber;
@property (nonatomic, copy) NSString * _Nonnull email;
@property (nonatomic) BOOL smsAllowed;
@property (nonatomic) BOOL emailAllowed;
@property (nonatomic, copy) NSString * _Nonnull birthday;
@property (nonatomic, copy) NSString * _Nonnull gender;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, DMTriggerType, open) {
/// 페이지 로드
  DMTriggerTypeLoadPage = 0,
/// 클릭(터치 이벤트)
  DMTriggerTypeClick = 1,
};


SWIFT_CLASS("_TtC14DataManagerSDK15DMViewedProduct")
@interface DMViewedProduct : EventModel
@property (nonatomic, copy) NSString * _Nonnull productId;
@property (nonatomic, copy) NSString * _Nonnull productName;
@property (nonatomic) NSInteger productPrice;
@property (nonatomic, copy) NSString * _Nonnull imageUrl;
@property (nonatomic, copy) NSString * _Nonnull productUrl;
@property (nonatomic) NSInteger productQty;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14DataManagerSDK7DMVisit")
@interface DMVisit : EventModel
@property (nonatomic, copy) NSString * _Nonnull deepLink;
- (nonnull instancetype)initWithPvInName:(NSString * _Nonnull)pvInName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14DataManagerSDK14DataManagerSDK")
@interface DataManagerSDK : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull SDK_VERSION;)
+ (NSString * _Nonnull)SDK_VERSION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable installReferrer;)
+ (NSString * _Nullable)installReferrer SWIFT_WARN_UNUSED_RESULT;
+ (void)setInstallReferrer:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL enableLog;)
+ (BOOL)enableLog SWIFT_WARN_UNUSED_RESULT;
+ (void)setEnableLog:(BOOL)value;
+ (void)initSDKWithAppKey:(NSString * _Nonnull)appKey SWIFT_METHOD_FAMILY(none);
+ (void)handleUrlWithUrl:(NSString * _Nonnull)url;
+ (void)addEventWithEvent:(EventModel * _Nonnull)event;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class WKWebView;

@interface DataManagerSDK (SWIFT_EXTENSION(DataManagerSDK))
+ (void)setWebViewWithWebView:(WKWebView * _Nonnull)webView hostUrl:(NSString * _Nonnull)hostUrl;
+ (void)webViewLoadFinishedWithWebView:(WKWebView * _Nonnull)webView currentUrl:(NSString * _Nonnull)currentUrl;
@end



@interface EventModel (SWIFT_EXTENSION(DataManagerSDK))
- (void)addCustomDataWithKey:(NSString * _Nonnull)key value:(id _Nonnull)value;
- (void)addCustomDataWithParam:(enum DMParams)key value:(id _Nonnull)value;
@end




#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
